import type { Pool } from "pg";
import type { TelegramConversationKey } from "../telegram/conversation.js";
type Key=TelegramConversationKey|string; const keyOf=(key:Key):TelegramConversationKey=>typeof key==="string"?{chatId:key,threadId:"0",userId:key}:key;
interface Row {chat_id:string;thread_id:string;user_id:string;scope:"core"|"all";current_settings:unknown;target_settings:unknown;invalid_attempts:number;expires_at:Date;created_at:Date;updated_at:Date;expected_reply_message_id:string|null;}
export interface PendingT2VReset {chatId:string;threadId:string;userId:string;scope:"core"|"all";currentSettings:unknown;targetSettings:unknown;invalidAttempts:number;expectedReplyMessageId:string|null;expiresAt:string;createdAt:string;updatedAt:string;}
const map=(r:Row):PendingT2VReset=>({chatId:r.chat_id,threadId:r.thread_id,userId:r.user_id,scope:r.scope,currentSettings:r.current_settings,targetSettings:r.target_settings,invalidAttempts:r.invalid_attempts,expectedReplyMessageId:r.expected_reply_message_id,expiresAt:r.expires_at.toISOString(),createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
export class T2VResetPendingRepository {
 constructor(private readonly db:Pool){}
 async get(input:Key):Promise<PendingT2VReset|null>{const k=keyOf(input);const r=await this.db.query<Row>(`SELECT chat_id,thread_id,user_id,scope,current_settings,target_settings,invalid_attempts,expires_at,created_at,updated_at,expected_reply_message_id FROM operator_pending_t2v_reset WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3`,[k.chatId,k.threadId,k.userId]);return r.rows[0]?map(r.rows[0]):null;}
 async begin(input:{key?:Key;chatId?:string;threadId?:string;userId?:string;scope:"core"|"all";currentSettings:unknown;targetSettings:unknown;expiresAt:Date}){const k=input.key?keyOf(input.key):{chatId:input.chatId!,threadId:input.threadId??"0",userId:input.userId??input.chatId!};await this.db.query(`INSERT INTO operator_pending_t2v_reset(chat_id,thread_id,user_id,scope,current_settings,target_settings,invalid_attempts,expires_at)VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,0,$7) ON CONFLICT(chat_id,thread_id,user_id) DO UPDATE SET scope=EXCLUDED.scope,current_settings=EXCLUDED.current_settings,target_settings=EXCLUDED.target_settings,invalid_attempts=0,expected_reply_message_id=NULL,expires_at=EXCLUDED.expires_at,updated_at=NOW()`,[k.chatId,k.threadId,k.userId,input.scope,JSON.stringify(input.currentSettings),JSON.stringify(input.targetSettings),input.expiresAt]);}
 async setExpectedReply(input:Key,messageId:string){const k=keyOf(input);await this.db.query(`UPDATE operator_pending_t2v_reset SET expected_reply_message_id=$4,updated_at=NOW() WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3`,[k.chatId,k.threadId,k.userId,messageId]);}
 async incrementInvalid(input:Key):Promise<PendingT2VReset|null>{const k=keyOf(input);const r=await this.db.query<Row>(`UPDATE operator_pending_t2v_reset SET invalid_attempts=LEAST(invalid_attempts+1,3),updated_at=NOW() WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3 RETURNING chat_id,thread_id,user_id,scope,current_settings,target_settings,invalid_attempts,expires_at,created_at,updated_at,expected_reply_message_id`,[k.chatId,k.threadId,k.userId]);return r.rows[0]?map(r.rows[0]):null;}
 async remove(input:Key){const k=keyOf(input);await this.db.query(`DELETE FROM operator_pending_t2v_reset WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3`,[k.chatId,k.threadId,k.userId]);}
 async expireDue(_input?:Key){const r=await this.db.query(`DELETE FROM operator_pending_t2v_reset WHERE expires_at<=NOW()`);return(r.rowCount??0)>0;}
}
