import type { Pool } from "pg";
import type { TelegramConversationKey } from "../telegram/conversation.js";

type PendingKey = TelegramConversationKey | string;
function keyOf(key: PendingKey): TelegramConversationKey { return typeof key === "string" ? { chatId: key, threadId: "0", userId: key } : key; }
interface PendingRow { chat_id:string; thread_id:string; user_id:string; phase:"awaiting_prompt"|"awaiting_confirmation"; prompt:string|null; settings_snapshot:unknown; invalid_attempts:number; expected_reply_message_id:string|null; expires_at:Date; created_at:Date; updated_at:Date; }
export interface PendingT2V { chatId:string; threadId:string; userId:string; phase:PendingRow["phase"]; prompt:string|null; settingsSnapshot:unknown; invalidAttempts:number; expectedReplyMessageId:string|null; expiresAt:string; createdAt:string; updatedAt:string; }
function map(row: PendingRow): PendingT2V { return {chatId:row.chat_id,threadId:row.thread_id,userId:row.user_id,phase:row.phase,prompt:row.prompt,settingsSnapshot:row.settings_snapshot,invalidAttempts:row.invalid_attempts,expectedReplyMessageId:row.expected_reply_message_id,expiresAt:row.expires_at.toISOString(),createdAt:row.created_at.toISOString(),updatedAt:row.updated_at.toISOString()}; }

export class T2VPendingRepository {
  constructor(private readonly db: Pool) {}
  async get(input: PendingKey): Promise<PendingT2V|null> { const k=keyOf(input); const r=await this.db.query<PendingRow>(`SELECT chat_id,thread_id,user_id,phase,prompt,settings_snapshot,invalid_attempts,expected_reply_message_id,expires_at,created_at,updated_at FROM operator_pending_t2v WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3`,[k.chatId,k.threadId,k.userId]); return r.rows[0]?map(r.rows[0]):null; }
  async beginPrompt(input: PendingKey, expiresAt: Date) { const k=keyOf(input); await this.db.query(`INSERT INTO operator_pending_t2v (chat_id,thread_id,user_id,phase,prompt,settings_snapshot,invalid_attempts,expires_at) VALUES ($1,$2,$3,'awaiting_prompt',NULL,NULL,0,$4) ON CONFLICT (chat_id,thread_id,user_id) DO UPDATE SET phase='awaiting_prompt',prompt=NULL,settings_snapshot=NULL,invalid_attempts=0,expected_reply_message_id=NULL,expires_at=EXCLUDED.expires_at,updated_at=NOW()`,[k.chatId,k.threadId,k.userId,expiresAt]); }
  async setPrompt(input: PendingKey,prompt:string,settings:unknown,expiresAt:Date):Promise<boolean>{ const k=keyOf(input); const r=await this.db.query(`UPDATE operator_pending_t2v SET phase='awaiting_confirmation',prompt=$4,settings_snapshot=$5::jsonb,invalid_attempts=0,expected_reply_message_id=NULL,expires_at=$6,updated_at=NOW() WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3 AND phase='awaiting_prompt'`,[k.chatId,k.threadId,k.userId,prompt,JSON.stringify(settings),expiresAt]);return (r.rowCount??0)>0; }
  async setExpectedReply(input: PendingKey,messageId:string){const k=keyOf(input);await this.db.query(`UPDATE operator_pending_t2v SET expected_reply_message_id=$4,updated_at=NOW() WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3`,[k.chatId,k.threadId,k.userId,messageId]);}
  async incrementInvalid(input: PendingKey):Promise<PendingT2V|null>{const k=keyOf(input);const r=await this.db.query<PendingRow>(`UPDATE operator_pending_t2v SET invalid_attempts=LEAST(invalid_attempts+1,3),updated_at=NOW() WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3 AND phase='awaiting_confirmation' RETURNING chat_id,thread_id,user_id,phase,prompt,settings_snapshot,invalid_attempts,expected_reply_message_id,expires_at,created_at,updated_at`,[k.chatId,k.threadId,k.userId]);return r.rows[0]?map(r.rows[0]):null;}
  async remove(input: PendingKey){const k=keyOf(input);await this.db.query(`DELETE FROM operator_pending_t2v WHERE chat_id=$1 AND thread_id=$2 AND user_id=$3`,[k.chatId,k.threadId,k.userId]);}
  async expireDue(_input?:PendingKey){const r=await this.db.query(`DELETE FROM operator_pending_t2v WHERE expires_at<=NOW()`);return(r.rowCount??0)>0;}
}
